name: Generate Documentation
description: Generates a documentation website from a swift package.

inputs:
  output-path:
    decription: The path containing the generated docs.
    required: false
    default: "./docs"
  working-directory:
    description: The directory containing the swift package.
    required: false
    default: ""
  hosting-base-path:
    description: The the website will be hosted.
    required: false
    default: ${{ github.event.repository.name }}
  minimum-access-level:
    description: The minimum access level that must be included in the docs.
    default: "public"
  swift-version:
    description: The version of swift used to execute the docC package plugin.
    required: true

runs:
  using: 'composite'

  steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ inputs.swift-version }}

      - name: Generate Documentation
        if: ${{ runner.os == 'Linux' }}
        run: swift $GITHUB_ACTION_PATH/src/main.swift --hosting-base-path ${{ inputs.hosting-base-path }} --output-path ${{ inputs.output-path }} --working-directory ${{ inputs.working-directory }} --minimum-access-level ${{ inputs.minimum-access-level }} --swift-bin "`which swift`"
        shell: bash
 
      - name: Generate Documentation
        if: ${{ runner.os == 'macOS' }}
        run: swift $GITHUB_ACTION_PATH/src/main.swift --hosting-base-path ${{ inputs.hosting-base-path }} --output-path ${{ inputs.output-path }} --working-directory ${{ inputs.working-directory }} --minimum-access-level ${{ inputs.minimum-access-level }} --swift-bin "`which swift`"
        shell: bash
